# Use the official Node.js image as a base
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port that the Express app listens on (typically 3000)
EXPOSE 5000

# Define the environment variable for the MongoDB connection string
# Assuming your MongoDB is running locally on the host machine at port 27017
ENV MONGODB_URI=mongodb+srv://neel:t8feV0YnA40PBVFU@inotebook-cluster.kba4w.mongodb.net/iNoteBook

# Command to start the Express app
CMD ["npm", "start"]
